version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_emotions
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./services/database:/var/lib/postgresql/data

  db_view:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kraken114@bk.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  emotions_wom:
    build: .
    restart: always
    container_name: emotion_wom
    command: python main.py
    environment:
      - VIDEO_SRC=videos/video.mp4
      - DROP_TABLE=False
    volumes:
      - .:/app
    ports:
      - "8100:8100"
