version: '3.8'

services:

  # backend_traffic_analyzer:
  #   build: .
  #   restart: always
  #   container_name: womans_emotions
  #   command: python main.py
  #   environment:
  #     - VIDEO_SRC=video/video.mp4
  #     # - ROADS_JSON=configs/entry_exit_lanes.json
  #     # - TABLE_NAME=traffic_info
  #     # - DROP_TABLE=False
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8100:8100"
  #   # блок, когда cuda будет
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #         - driver: nvidia
  #   #           count: all
  #   #           capabilities: [gpu]
  #   networks:
  #     - prod_network
  #   env_file:
  #     - secrets.txt

  db:
    container_name: database
    image: postgres:15
    restart: always
    ports:
      - "5488:5432"
    volumes:
      - ./services/database:/var/lib/postgresql/data
    networks:
      - prod_network
    env_file:
      - secrets.txt

  db_view:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kraken114@bk.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    networks:
      - prod_network
    env_file:
      - secrets.txt
  # grafana:
  #   container_name: grafana_building
  #   image: grafana/grafana:latest
  #   environment:
  #     TZ: "Europe/Moscow"
  #     GF_ALLOW_EMBEDDING: true
  #     GF_PANELS_DISABLE_SANITIZE_HTML: true
  #   restart: unless-stopped
  #   ports:
  #     - "3111:3000"
  #   volumes:
  #     - ./services/grafana:/var/lib/grafana
  #   networks:
  #     - prod_network
  #   env_file:
  #     - secrets.txt

volumes:
  db:
  db_view:
    # pg_data_wh:
    # pg_grafana:
    # grafana:


networks:
  prod_network:
    driver: bridge
