version: '3.8'

services:

  emotions_data:
    build: .
    restart: always
    container_name: emotions_data
    command: python main.py
    environment:
      - TABLE_NAME=russia
    volumes:
      - .:/app
    ports:
      - "8100:8100"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    networks:
      - pg-network
  postgresS:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grim
    volumes:
      - postgres_files:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kraken114@bk.ru
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    networks:
      - pg-network
    restart: unless-stopped
    depends_on:
      - postgresS

volumes:
  postgres_files:


networks:
  pg-network:
    driver: bridge
