version: '3.9'

services:
  emotions_wom:
    build: .
    restart: always
    container_name: emotion_wom
    command: python main.py
    environment:
      - VIDEO_SRC=videos/video.mp4
      # - TABLE_NAME=emotions
      - DROP_TABLE=False
      # - DISPLAY=emotions_wom:0.0

    volumes:
      - .:/app
    ports:
      - "8100:8100"
    networks:
      - prod_network
    env_file:
      - secrets.txt
  pg_db:
    container_name: pg_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_emotions
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./services/db:/var/lib/postgresql/data
    networks:
      - prod_network
    env_file:
      - secrets.txt

  db_view:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kraken114@bk.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - prod_network
    env_file:
      - secrets.txt

volumes:
  db:
    # pg_grafana:
    # grafana:

networks:
  prod_network:
    driver: bridge
