
# ------------------------------------------------- NODES --------------------------------------------------

video_reader:
  src: video/video.mp4 #${oc.env:VIDEO_SRC} # путь до файла обработки или номер камеры (int) или ссылки на m3u8 / rtsp поток
  # skip_secs : 0  # считываем кадры раз в <skip_secs> секунд
  # roads_info: ${oc.env:ROADS_JSON} # json файл с координатами дорог на видео


detection_node:
  weight_pth: model/best.pt  # Путь до модели .pt или .engine (TensorRT)
  classes_to_detect: [1,2,3,4,5,6]  # весь транспорт из классов COCO
  confidence: 0.10  # Порог уверенности детектора (чем больше значение, тем меньше находит)
  iou: 0.7  # Порог NMS (чем больше значение, тем больше находит)
  imgsz: 640  # Ресайз при инференсе (640 по умолчанию)